language: groovy
jdk:
- openjdk7
script: ./profiles/travis-build.sh
env:
  global:
  - TERM=dumb
  - GIT_NAME="Graeme Rocher"
  - GIT_EMAIL="graeme.rocher@gmail.com"
  - secure: AL9fkFVvXqr3+ZM5O3+qnA0lpDskf/1jz4NrAsL/TCcDUsRZH4bdR3gwVUqHjt7+yr42/adwOliwCIvzwJzbW8eeEetcZcNen+WBf03lw04zTFACWW6Yes49vZ6qGTKxAVuVQ8bd1yQzJZUTta7/Nu4Aet+Eq1rZEyz9WvSF28U=
  - secure: KB9glHCgYfgR2uXxRBghB9Rp9TGth/KhfzdeNeNbXLrqcoZGXsjrFDLGs2eH3K+4oYKPwcOiIBDUCK3twSsMOx0hcSCVTA3q1cJx/Qhjsv/fneAkq4SFN6Yqsgeksw1hbZRGdtufhGFtOAsLnTEVYxjFCxIKQ9fAAt1mSzSFqpU=
  - secure: JJJSHR09fppZTNlhJ6Tk57rn4U9ldH/6Dwke90vUhcxMwzrMTM1mfyuQ9CKFgXtz2WXfhAPsOrKu6oEISbdu0PoNK4YBFd4xl4jQmR9NEJ7gi0XnkM/v0HmNtJe7kfHvu3nHv+LzOfFXPAE67kpNC728Yc3jXCCQyNbqVfkEv7o=
  - secure: dC5FCqAeVGrHzWN95D8r51bUiuCyvxIWnAT9jj4up9ohbjjSBb9bvVWUPlqlmQZ3QoTOqRJ9935npscmHuxxpYOCufZ8RcXY/fp3w20R45RXhfG1ve4CdPWrDnkO6e2i7S6kbSoD8+YN2eex2pEfWXXZxHeVJ7U1QTwZk+9ScjI=
  - secure: Y9k0Q1xxwNGG1JrBkJ01XmjQlwE77j3RFCe8GMoSEA2yfBn6n1wkhC5eI0d5uZCjS38pCW2fLtUoLxDdDCXk3FBNM5usW2VOoldVbkEarwFo1hn/g2LSz0pMbslQR9/MV6BGrvLcDw+jztN+S9aNhcfFGHANBaXvHVDDOxSCMr4=
